# Generated by Django 4.2.5 on 2024-05-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='location',
            field=models.CharField(default='Default Location', max_length=200),
        ),
    ]
